-- AlterTable
ALTER TABLE "PhoneNumber" ADD COLUMN "ringAll" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "source" TEXT NOT NULL DEFAULT 'TWILIO',
ADD COLUMN "voicemailEnabled" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "twilioSid" DROP NOT NULL;
